# Generated by Django 6.0.3 on 2026-03-13 03:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
