# Generated by Django 6.0.3 on 2026-03-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deline',
            new_name='deadline',
        ),
    ]
