# Generated by Django 6.0.3 on 2026-03-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='Contract',
            new_name='contract',
        ),
    ]
